### PR TITLE
Updates ESLint to 3.0.0

### PR DESCRIPTION
**Pull request by takempf**
#### Related
- https://github.com/meadow/boilerplate/pull/2

---
#### Objective

Update our eslint config so that it works properly with eslint 3.0

---
#### What I did

Followed both [eslint migration guides](http://eslint.org/docs/user-guide/migrating-to-2.0.0) since we were 2 versions behind...

---
#### How to verify
- Pull this branch
- `npm install`
- `npm run lint`
- Linting should pass

### CODE REVIEW

**Comment by takempf** [comment]
@rickharrison I looked up the "no 'use strict' in ES6 modules thing" and got a couple sources:
- https://hacks.mozilla.org/2015/08/es6-in-depth-modules/
- https://github.com/eslint/eslint/blob/master/docs/rules/strict.md

The consensus seems to be that "use strict" is pointless in ES6 modules because they're _always_ strict, whether we do or do not have "use strict" in there.

**Comment by rickharrison** [comment]
Yea, I saw that. But the problem is that we aren't ever actually running es6 modules. It is compiled to something else.

**Comment by rickharrison** [comment]
I'm looking into it now. I'll figure it out and then merge this before lunch.

**Comment by takempf** [comment]
True, but ES6 modules don't work natively anywhere at the moment, so they must be assuming this is going through babel...

**Pull request merged**
